
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxgsdqblwshpktuurmgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4Z3NkcWJsd3NocGt0dXVybWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MzgyMjYsImV4cCI6MjA2MDAxNDIyNn0.8ibP9MRTAk9kztHll7SueFRcJPDi6jq0b4Oo0liSF9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storage: localStorage,
    autoRefreshToken: true,
  }
});
